version: "3.8"

services:
  n8n:
    image: n8nio/n8n:1.123.13
    container_name: n8n-main
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=XiuDouMao
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

  task-runners:
    image: n8nio/runners:1.123.13
    container_name: n8n-runners
    restart: always
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=XiuDouMao
    depends_on:
      - n8n

volumes:
  n8n_data:
